CONSTANTS-$(CONFIG_ENABLE_ASSERT) += -DENABLE_ASSERT
CONSTANTS-$(CONFIG_IDMAN_PD) += -DIDMAN_PD
CONSTANTS-1 += -DNTTCOM

CFLAGS += -I$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/idman/lib/ccid -I$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/idman/lib/iccard -I$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/idman/lib/idman_pkcs11
CFLAGS += -I$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/idman/lib/pcsc -I$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/idman/lib/pkcs11 -I$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/idman/lib/standardio
CFLAGS += -I$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/idman/lib/user
CFLAGS += -I$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/drivers -I$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/drivers/usb

objs-1 += IDMan_CcAtr.o IDMan_CcIfdhandler.o IDMan_CcInitCard.o
objs-1 += IDMan_CcProtocol.o IDMan_CcReaderControl.o IDMan_CcUsb.o
