CONSTANTS-$(CONFIG_ENABLE_ASSERT) += -DENABLE_ASSERT
CONSTANTS-$(CONFIG_IDMAN_PD) += -DIDMAN_PD
CONSTANTS-1 += -DNTTCOM

CFLAGS += -I$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/idman/ccid -I$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/idman/iccard -I$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/idman/idman_pkcs11 -I$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/idman/pcsc
CFLAGS += -I$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/idman/pkcs11 -I$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/idman/standardio -I$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/idman/user

CFLAGS += -I$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/drivers/usb -I$(k2e)/bitvisor/$(k2e)/bitvisor/$(k2e)/bitvisor/idman

objs-1 += user.o
subdirs-1 += ccid iccard idman_pkcs11 pcsc pkcs11 standardio
